// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectTestSem3_Server.Data;

namespace projectTestSem3_Server.Migrations
{
    [DbContext(typeof(projectTestSem3_ServerContext))]
    [Migration("20220618085922_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projectTestSem3_Server.Models.BloodProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_BloodDnt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("historyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("historyId");

                    b.ToTable("BloodProvider");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("historyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("historyId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_bloodProvider")
                        .HasColumnType("int");

                    b.Property<int>("Id_guest")
                        .HasColumnType("int");

                    b.Property<int>("Id_mobiLink")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.MoibiLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_guest")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("historyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("historyId");

                    b.ToTable("MoibiLink");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.UserAcc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAcc");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.BloodProvider", b =>
                {
                    b.HasOne("projectTestSem3_Server.Models.History", "history")
                        .WithMany("bloodProviders")
                        .HasForeignKey("historyId");

                    b.Navigation("history");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.Guest", b =>
                {
                    b.HasOne("projectTestSem3_Server.Models.History", "history")
                        .WithMany("guests")
                        .HasForeignKey("historyId");

                    b.Navigation("history");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.MoibiLink", b =>
                {
                    b.HasOne("projectTestSem3_Server.Models.History", "history")
                        .WithMany("moibiLinks")
                        .HasForeignKey("historyId");

                    b.Navigation("history");
                });

            modelBuilder.Entity("projectTestSem3_Server.Models.History", b =>
                {
                    b.Navigation("bloodProviders");

                    b.Navigation("guests");

                    b.Navigation("moibiLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
